// Deepcopy implementations. Normally generated by controller-gen; hand-written
// here so the repo builds without the code-generation toolchain installed.
// Semantics match the generator: deep copies, nil-safe, and DeepCopyObject
// returns nil for a nil receiver so a typed-nil never reaches the API machinery.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- Placement ---

func (in *Placement) DeepCopyInto(out *Placement) { *out = *in }

func (in *Placement) DeepCopy() *Placement {
	if in == nil {
		return nil
	}
	out := new(Placement)
	in.DeepCopyInto(out)
	return out
}

// --- Spec ---

func (in *InferenceClusterSpec) DeepCopyInto(out *InferenceClusterSpec) { *out = *in }

func (in *InferenceClusterSpec) DeepCopy() *InferenceClusterSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// --- Status ---

func (in *InferenceClusterStatus) DeepCopyInto(out *InferenceClusterStatus) {
	*out = *in
	if in.Placements != nil {
		out.Placements = make([]Placement, len(in.Placements))
		copy(out.Placements, in.Placements)
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *InferenceClusterStatus) DeepCopy() *InferenceClusterStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// --- InferenceCluster ---

func (in *InferenceCluster) DeepCopyInto(out *InferenceCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *InferenceCluster) DeepCopy() *InferenceCluster {
	if in == nil {
		return nil
	}
	out := new(InferenceCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject satisfies runtime.Object.
func (in *InferenceCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- InferenceClusterList ---

func (in *InferenceClusterList) DeepCopyInto(out *InferenceClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]InferenceCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *InferenceClusterList) DeepCopy() *InferenceClusterList {
	if in == nil {
		return nil
	}
	out := new(InferenceClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject satisfies runtime.Object.
func (in *InferenceClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
